#!/bin/bash
cat <<-EOF
Selecciona tu distro de 64 bits
1 Ubuntu 16.04 LTS (y derivados)
2 OpenSuse
3 Manjaro
4 Fedora 25
5 Debian Testing (Stretch)
6 Debian Stable (Jessie)
7 Salir
EOF
  read respuesta

  case $respuesta in
    1) echo "Añadimos los repositorios"
      sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian xenial contrib";
      #Añadimos las claves del repositorio:
      sudo apt-key add oracle_vbox_2016.asc;
      sudo apt-key add oracle_vbox.asc;
      sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      sudo add-apt-repository ppa:libreoffice/libreoffice-5-2;
      sudo apt update && sudo apt upgrade;
      sudo apt install git;
      sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual;
      sudo apt-get install docker-engine;
      sudo apt install virtualbox;
      echo "Disfruta de tus programas"
      ;;
    2) echo "¡Muy buena elección, es nuestra especialidad!";;
    3) echo "Actualizamos los repositorios y los programas instalados"
      sudo pacman-mirrors -g;
      sudo pacman -Syu;
      sudo pacman -S virtualbox && pacman -S git;
      yaourt -S sublime-text-dev;
      yaourt -S visual-studio-code;
      pacman -S git;
    ;;
    4) echo "Pongámonos el sombrero entonces ;)";;
      echo "Actalizando el sistema"
      sudo dnf update -y;
      echo "Agregando los repositorios RPM Fusion"
      sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
      echo "Configurando rpm fusion"
      sudo dnf update -y;
      #Apps opcionales
      # echo "Instalando vlc"
      # sudo dnf -y install vlc;
      # echo "Instalando Plataforma de juegos steam"
      # sudo dnf -y install steam;
      # Veré luego lo esencial en Fedora (GNOME)
  ;;
  5) echo "Debian Testing otro de nuestros favoritos <3"
   echo "Actualizando tu sistema"
     sudo apt update && sudo apt upgrade;
   echo "Instalando utilidades básicas del sistema"
     sudo apt -y install rednotebook clementine apt-xapian-index gdebi gksu firmware-linux ttf-freefont ttf-mscorefonts-installer ttf-bitstream-vera ttf-dejavu ttf-liberation gparted;
   echo "Instalando Codecs Multimedia"
     sudo apt -y install gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad gstreamer0.10-fluendo-mp3 gstreamer0.10-pulseaudio;
   echo "Instalando temas (Para que quede guapo)
     sudo apt -y install arc-theme numix-gtk-theme numix-icon-theme;
    #apps nonfree
    #echo "instalando steam"
    #sudo dpkg --add-architecture i386 && sudo apt -y install steam
   ;;
  6) echo "El buen y estable Debian"
       echo "En progreso"
       ;;
  7) echo "Hasta luego"
       exit;;
    *) echo "Debes escoger una opción válida";;
    esac
