#!/bin/bash
cat <<-EOF
Selecciona tu distro de 64 bits
1 Ubuntu 16.04 LTS (y derivados)
2 OpenSuse
3 Manjaro
4 Fedora 25
5 Debian Testing (Stretch)
6 Salir
EOF
  read respuesta

  case $respuesta in
    1) echo "Añadimos los repositorios"
      sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian xenial contrib";
      #Añadimos las claves del repositorio:
      sudo apt-key add oracle_vbox_2016.asc;
      sudo apt-key add oracle_vbox.asc;
      sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      sudo add-apt-repository ppa:libreoffice/libreoffice-5-2;
      sudo apt update && sudo apt upgrade;
      sudo apt install git;
      sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual;
      sudo apt-get install docker-engine;
      sudo apt install virtualbox;
      echo "Disfruta de tus programas"
      ;;
    2) echo "¡Muy buena elección, es nuestra especialidad!";;
    3) echo "Actualizamos los repositorios y los programas instalados"
      sudo pacman-mirrors -g;
      sudo pacman -Syu;
      sudo pacman -S virtualbox && pacman -S git;
      yaourt -S sublime-text-dev;
      yaourt -S visual-studio-code;
      pacman -S git;
    ;;
    4) echo "Pongámonos el sombrero entonces"
      echo "Actualizando el sistema"
      sudo dnf update -y;
      echo "Agregando los repositorios RPM Fusion"
      sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
      echo "Configurando rpm fusion"
      sudo dnf update -y;
      sudo dnf -y install vlc;
      sudo dnf -y install steam;
      # Veré luego lo esencial en Fedora (GNOME)
  ;;
  5) echo "Sabía que acabarías aquí"
        #Añadimos las claves del repositorio:
      sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian jessie contrib";
      sudo apt-key add oracle_vbox_2016.asc;
      sudo apt-key add oracle_vbox.asc;
      sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      sudo add-apt-repository ppa:libreoffice/libreoffice-5-2;
      sudo apt update && sudo apt upgrade;
      sudo apt install git;
      sudo apt install linux-image-extra-$(uname -r) linux-image-extra-virtual;
      sudo apt install docker-engine;
      sudo apt install virtualbox;
    #Optimización del sistema
      sudo apt install apt-transport-https;
      sudo apt install menulibre alacarte;
      sudo apt install prelink preload;
    #Uso de batería
      sudo apt install tlp && sudo tlp start; #Aplicación de los repos, mejora el rendimiento de la batería deteniendo procesos inservibles si la máquina tiene poca energía
    #Soporte de procesadores
      sudo apt install amd64-microcode;
      sudo apt install intel-microcode;
    #Herramientas gráficas no indispensables
      #sudo apt install inkscape gimp;
    #Utilidades del sistema
      sudo apt install debian-goodies;
      sudo apt install debianutils;
      sudo apt install laptop-detect;
      sudo apt install gdebi;
      sudo apt install gksu;
      #Versión mas reciente de Firefox (No ESR)
      #En progreso
      echo "Disfruta de tus programas"
      ;;
  6) echo "Hasta luego"
       exit;;
    *) echo "Debes escoger una opción válida"
    ;;
    esac
